CREATE DATABASE PETSHOP;

USE PETSHOP;

CREATE TABLE FUNCIONARIO
(
    REGISTRO INT PRIMARY KEY,
    NOME VARCHAR(20),
    CARGO CHAR(12) ,
    SALARIO FLOAT
);

CREATE TABLE SERVIÇOS_FUNIONARIOS
(
SERVIÇOSINT,
REGISTRO_FUNIONARIOS INT,
FOREIGN KEY (REGISTRO) 
REFERENCES SERVIÇOS

);



CREATE TABLE SERVIÇOS
(
    ID  INT PRIMARY KEY
    NOTA VARCHAR(45),
    VACINA VARCHAR(45),
    CONSULTA VARCHAR(45),
    TOSA VARCHAR(45),
    BANHO VARCHAR(45),
)
CREATE TABLE PEDIDO
(
    ID PEDIDO INT PRIMARY KEY,
    ID PRODUTOS INT,
    ID SERVIÇOS INT,
    VALOR FLOAT ,
)


CREATE TABLE SERVIÇOS_PEDIDOS
(
    SERVIÇOS INT,
    PEDIDO INT,
    FOREIGN KEY (SERVIÇOS), 
    REFERENCES ID(PEDIDO),
)

CREATE TABLE PRODUTOS
(
    ID PRODUTOS INT PRIMARY KEY,
    NOME VARCHAR(45),
    MARCA VARCHAR(45),
    FORNECEDOR VARCHAR(45),
    VALIDADE DATE,
    ESTOQUE FLOAT,

)

CREATE TABLE PEDIDO_PRODUTOS
(
PEDIDO INT,
PRODUTO INT,
PRIMARY KEY(ID,PEDIDO),
FOREIGN KEY (PEDIDO) ,
REFERENCES ID(PRODUTO),
FOREIGN KEY (PRODUTO),
)


CREATE TABLE PAGAMENTO (
    ID PAGAMENTO INT PRIMARY KEY,
    ID PEDIDO INT,
    FORMA DE PAGAMENTO CHAR(10);
    FOREIGN KEY(PEDIDO),
    REFERENCES ID(PEDIDO)
);

CREATE TABLE PAGAMENTO_FORMA_PAGAMENTO
(
ID FORMA_PAGAMENTO INT PRIMARY KEY;
pix FLOAT,
DINHEIRO FLOAT,
DEBITO FLOAT,
CREDITO FLOAT
);
CREATE TABLE FORMA_PAGAMENTO
(
    ID PAGAMENTO INT(100) PRIMARY KEY;
    ID FORMA_PAGAMENTO INT,
    FOREIGN KEY ID(PAGAMENTO),
    REFERENCES ID(FORMA_PAGAMENTO)
);

CREATE TABLE CLIENTE(
CPF CHAR(11) PRIMARY KEY,
NOME VARCHAR(80),
ENDEREÇO VARCHAR(80),
CEP CHAR(8),
CLIENTECOL VARCHAR(45),
ID_PET INT;
NUMERO VARCHAR(10),
BAIRRO VARCHAR(100),
)

CREATE TABLE PEDIDO_CLIENTE (
ID PEDIDO INT,
CLIENTE CPF CHAR(11),
PRIMARY KEY ID(PEDIDO),
FOREIGN KEY (CPF), 
REFERENCES CLIENTE(CPF),
)

CREATE TABLE TELEFONE(
    CELULAR VARCHAR(15) PRIMARY KEY,
    TELEFONE_FIXO VARCHAR(15),
    TELEFONE_RECADO VARCHAR(15),
     FOREIGN KEY(CLIENTE);
    REFERENCES CPF CHAR(11);
)

CREATE TABLE PET(
    ID PET INT PRIMARY KEY,
    ESPECIE VARCHAR(45),
    NOME VARCHAR(45),
    CPF VARCHAR(45),
    COR VARCHAR(45),
    DATA_NASCIMENTO DATE
);

CREATE TABLE CLIENTE_PET
(
    CLIENTE_CPF CHAR(11),
    ID PET INT,
    FOREIGN KEY(CLIENTE),
    REFERENCES CPF CHAR(11)

);